apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: chat-app-ns
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: mongodb-premium-sc
  accessModes:
    - ReadWriteOnce
