apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-app-cm
  namespace: chat-app-ns
data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongodb:27017/chat_app"
  BACKEND_URI: "http://chat-app-backend-svc:5000"
