apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-svc
  namespace: chat-app-ns
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
spec:
  selector:
    app: chat-app-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
  sessionAffinity: ClientIP
