apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: chat-app-sc
  namespace: chat-app-ns
provisioner: file.csi.azure.com

parameters:
  skuName: Standard_LRS

mountOptions:
  - dir_mode=0755
  - file_mode=0644
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict

reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true