apiVersion: apps/v1
kind: Deployment 
metadata:
  name: chat-app-backed-deploy
  namespace: chat-app-ns
  labels:
    app: chat-app-backend

spec:
  replicas: 4

  selector:
    matchLabels:
      app: chat-app-backend

  template:  
    metadata:
      labels: 
        app: chat-app-backend

    spec:
      containers:
        - name: chat-app-backend
          image: sree471/chatb:1
          imagePullPolicy: Always

          ports: 
            - containerPort: 5000    

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-app-cm
                  key: PORT

            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-app-cm
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-app-secret
                  key: JWT_SECRET

          volumeMounts:
            - name: chat-app-volume
              mountPath: "/app/uploads/chat"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: chat-app-volume
          persistentVolumeClaim:
            claimName: chat-app-pvc